---

repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.20.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: markdownlint
        files: \.(markdown|md)$
        additional_dependencies: [mdl]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
      - id: pylint
        files: \.(py)$
        args: [--disable=import-error]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
